import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';

class FirebaseService {
  // Singleton pattern
  static final FirebaseService _instance = FirebaseService._internal();
  factory FirebaseService() => _instance;
  FirebaseService._internal();

  // Initialization
  Future<void> init() async {
    try {
      // Note: DefaultFirebaseOptions is generated by FlutterFire CLI.
      // If not present, we assume Firebase is initialized in main.dart
      // or we use a manual initialization if needed.
      await Firebase.initializeApp();
    } catch (e) {
      print('Firebase init error: $e');
    }
  }

  // Getters for Firebase instances
  FirebaseFirestore get db => FirebaseFirestore.instance;
  FirebaseAuth get auth => FirebaseAuth.instance;
}
