import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../providers/offer_provider.dart';
import '../../providers/auth_provider.dart';
import '../../core/theme/app_theme.dart';
import '../../models/offer_model.dart';

class AddOfferScreen extends StatefulWidget {
  const AddOfferScreen({super.key});

  @override
  State<AddOfferScreen> createState() => _AddOfferScreenState();
}

class _AddOfferScreenState extends State<AddOfferScreen> {
  int _currentStep = 0;
  
  // Step 1 Controllers
  int? _selectedType; // 1: Property, 2: Car
  int? _selectedTrans; // 1: Sell, 2: Rent
  String? _selectedCat;

  // Step 2 Controllers
  final TextEditingController _priceController = TextEditingController();
  final TextEditingController _locController = TextEditingController();
  final TextEditingController _descController = TextEditingController();
  final TextEditingController _specController = TextEditingController();

  // Step 3 State
  List<String> _selectedImages = [];
  String? _deedType;
  Map<String, List<String>> _availability = {};

  void _nextStep() {
    if (_currentStep < 2) setState(() => _currentStep++);
  }

  void _prevStep() {
    if (_currentStep > 0) setState(() => _currentStep--);
  }

  Future<void> _submitOffer() async {
    final authProvider = Provider.of<AuthProvider>(context, listen: false);
    final offerProvider = Provider.of<OfferProvider>(context, listen: false);

    if (_selectedType == null || _priceController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('يرجى إكمال البيانات الأساسية')),
      );
      return;
    }

    // Create Offer Object
    OfferModel newOffer = OfferModel(
      id: '', // Generated by Firebase
      uId: authProvider.currentUser?.uid ?? '',
      title: '${_selectedCat} في ${_locController.text}',
      type: _selectedType!,
      trans: _selectedTrans ?? 1,
      cat: 0, // Mapping cat name to ID should be handled
      prc: double.tryParse(_priceController.text) ?? 0.0,
      loc: _locController.text,
      desc: _descController.text,
      spec: _specController.text,
      imgs: _selectedImages,
      sts: 0, // Pending review
      iPub: 0,
      avl: _availability,
      dtC: DateTime.now(),
      dtU: DateTime.now(),
    );

    bool success = await offerProvider.addOffer(newOffer);
    if (success) {
      Navigator.pop(context);
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('تم إرسال عرضك للمراجعة بنجاح')),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('إضافة عرض جديد'),
        backgroundColor: Colors.transparent,
      ),
      body: Stepper(
        type: StepperType.vertical,
        currentStep: _currentStep,
        onStepTapped: (step) => setState(() => _currentStep = step),
        onStepContinue: _nextStep,
        onStepCancel: _prevStep,
        steps: [
          _buildStep1(),
          _buildStep2(),
          _buildStep3(),
        ],
      ),
    );
  }

  Step _buildStep1() {
    return Step(
      title: const Text('الأساسيات', style: TextStyle(color: AppTheme.primaryGold, fontWeight: FontWeight.bold)),
      content: Column(
        children: [
          _buildDropdown('نوع العرض', ['عقار', 'سيارة'], (val) => setState(() => _selectedType = val == 'عقار' ? 1 : 2)),
          const SizedBox(height: 20),
          _buildDropdown('نوع المعاملة', ['بيع', 'إيجار'], (val) => setState(() => _selectedTrans = val == 'بيع' ? 1 : 2)),
          const SizedBox(height: 20),
          _buildDropdown('التصنيف', ['شقة', 'فيلا', 'أرض', 'سيدان', 'SUV', 'دفع رباعي'], (val) => setState(() => _selectedCat = val)),
        ],
      ),
      isActive: _currentStep >= 0,
    );
  }

  Step _buildStep2() {
    return Step(
      title: const Text('التفاصيل', style: TextStyle(color: AppTheme.primaryGold, fontWeight: FontWeight.bold)),
      content: Column(
        children: [
          TextField(
            controller: _priceController,
            keyboardType: TextInputType.number,
            decoration: const InputDecoration(labelText: 'السعر المتوقع (ل.س)'),
          ),
          const SizedBox(height: 15),
          TextField(
            controller: _locController,
            decoration: const InputDecoration(labelText: 'الموقع / المنطقة'),
          ),
          const SizedBox(height: 15),
          TextField(
            controller: _descController,
            maxLines: 3,
            decoration: const InputDecoration(labelText: 'وصف مختصر للعرض'),
          ),
          const SizedBox(height: 15),
          TextField(
            controller: _specController,
            maxLines: 3,
            decoration: const InputDecoration(labelText: 'المواصفات الفنية'),
          ),
        ],
      ),
      isActive: _currentStep >= 1,
    );
  }

  Step _buildStep3() {
    return Step(
      title: const Text('المرفقات والمواعيد', style: TextStyle(color: AppTheme.primaryGold, fontWeight: FontWeight.bold)),
      content: Column(
        children: [
          ElevatedButton.icon(
            onPressed: () {
              // Image picker logic here
              setState(() => _selectedImages.add('https://via.placeholder.com/150'));
            },
            icon: const Icon(Icons.image),
            label: const Text('إضافة صور (حد أقصى 6)'),
          ),
          Wrap(
            children: _selectedImages.map((img) => Padding(
              padding: const EdgeInsets.all(5),
              child: Image.network(img, width: 60, height: 60, fit: BoxFit.cover),
            )).toList(),
          ),
          const SizedBox(height: 20),
          _buildDropdown('نوع السند', ['طابو أخضر', 'حجة', 'وكالة', 'غير متوفر'], (val) => setState(() => _deedType = val)),
          const SizedBox(height: 20),
          const Text('المواعيد المتاحة للمعاينة', style: TextStyle(color: AppTheme.textWhite)),
          const SizedBox(height: 10),
          SizedBox(
            width: double.infinity,
            height: 55,
            child: ElevatedButton(
              onPressed: _submitOffer,
              child: const Text('نشر العرض الآن'),
            ),
          ),
        ],
      ),
      isActive: _currentStep >= 2,
    );
  }

  Widget _buildDropdown(String label, List<String> items, Function(String) onSelected) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(label, style: const TextStyle(color: AppTheme.textGrey)),
        const SizedBox(height: 5),
        DropdownButtonFormField<String>(
          value: null,
          items: items.map((i) => DropdownMenuItem(value: i, child: Text(i))).toList(),
          onChanged: (val) => onSelected(val!),
          decoration: const InputDecoration(border: OutlineInputBorder()),
        ),
      ],
    );
  }
}
